import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'; 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="bg-gray-800 text-white w-64 min-h-screen p-4 fixed top-0 left-0 bottom-0">
        <div className="text-2xl font-semibold mb-6">Manage EV</div>
        <ul>
          <li className="mb-2">
            <Link href="/">
              Home
            </Link>
          </li>
          <li className="mb-2">
            <Link href="/vehicles">
              Vehicles
            </Link>
          </li>
          <li className="mb-2">
            <Link href="/user/signUp">
              Sign Up
            </Link>
          </li>
          <li className="mb-2">
            <Link href="/user/login">
              Login
            </Link>
          </li>
        </ul>
      </nav>
        {children}
      </body>
    </html>
  )
}

