import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <h1>navbar</h1>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/vehicles">Vehicles</a></li>
            <li><a href="/user/signUp">Sign Up</a></li>
            <li><a href="/user/login">Login</a></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
